- name: Leave Current Swarm
  docker_swarm:
    state: absent
    force: true

- name: Add Node 1
  docker_swarm:
    state: join
    advertise_addr: 35.246.95.91
    join_token: "{{ hostvars['join-token']['value'] }}"
    remote_addrs: [ '10.154.0.38:2377' ]

- name: Add Node 2
  docker_swarm:
    state: join
    advertise_addr: 34.89.36.81
    join_token: "{{ hostvars['join-token']['value'] }}"
    remote_addrs: [ '10.154.0.38:2377' ]
