- name: Install Requirements For Docker
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent 
    - software-properties-common
    - python3
    - python3-pip
    state: latest
    update_cache: true

- name: Add GPG Key  
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install Pip
  pip: 
   name: docker-py

- name: Add Apt Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
    update_cache: true

- name: Install Docker
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest  
    update_cache: true

- name: Drain Nodes
  docker_swarm:
    state: absent
    force: true
