---
- name: Initialise Swarm
  docker_swarm:
    state: present
  
  register: docker_swarm_info

- name: Debug Swarm Info
  debug:
    var: docker_swarm_info

- name: Store Swarm Info
  add_host:
    name: info
    dockerinfo: docker_swarm_info
    dockertoken: "{{docker_swarm_info.swarm_facts.JoinTokens.Worker }}" 

- name: Retrieve Info
  debug:
    var: "{{ hostvars['info']['dockerinfo'] }}"

- name: Retrieve Token
  debug:
    var: "{{ hostvars['info']['dockertoken'] }}"
